version: '3.3'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "14000:6379"

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:9000
    env_file:
      - .env
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
